adamantine-sim/adamantine

- application/adamantine.cc
- source/Physics.hh
- source/ThermalPhysics.hh
- source/ThermalPhysics.templates.hh
- tests/test_thermal_physics.cc
> Add initial temperature.

- source/ElectronBeam.templates.hh
- source/MaterialProperty.hh
> Change default value of the beam diameter

- source/ElectronBeam.hh
- source/ElectronBeam.templates.hh
- source/Geometry.hh
- source/Geometry.templates.hh
- source/ImplicitOperator.hh
- source/ImplicitOperator.templates.hh
- source/MaterialProperty.hh
- source/MaterialProperty.templates.hh
- source/NewtonSolver.hh
- source/Operator.hh
- source/Physics.hh
- source/PostProcessor.hh
- source/PostProcessor.templates.hh
- source/ThermalOperator.hh
- source/ThermalOperator.templates.hh
- source/ThermalPhysics.hh
- source/ThermalPhysics.templates.hh
- source/types.hh
- source/utils.hh
> Change header guards.

- AUTHORS.md
- README.md
> Improve README.

- application/adamantine.cc
- source/ElectronBeam.hh
- source/ElectronBeam.templates.hh
- tests/test_electron_beam.cc
> Rewind the position in the list of beam positions

- application/adamantine.cc
- source/CMakeLists.txt
- source/Timer.cc
- source/Timer.hh
- tests/CMakeLists.txt
- tests/test_timer.cc
> Add timer.

- application/adamantine.cc
> Fix a bug 

- source/CMakeLists.txt
- source/ElectronBeamHeatSource.cc
- source/ElectronBeamHeatSource.hh
- source/GoldakHeatSource.cc
- source/GoldakHeatSource.hh
- source/HeatSource.cc
- source/HeatSource.hh
- tests/CMakeLists.txt
- tests/test_heat_source.cc
This is still free-floating in the code. My next PR will be to replace the use of ElectronBeam with this.
> New HeatSource class (and electron beam/Goldak derived classes)

- ci/Dockerfile
- source/ThermalPhysics.templates.hh
- tests/test_implicit_operator.cc
- tests/test_post_processor.cc
- tests/test_thermal_operator.cc
- tests/test_thermal_operator_device.cu
Update deal.II and add Trilinos and its dependencies. This should allow us to read exodus file. 
Everybody will need to update deal.II.
> Update Docker images

- README.md
- application/adamantine.hh
Simple change so that it doesn't output every time step. I'll wait until #75 is merged in and add the README text (hence the WIP).
> Add an input parameter for the output frequency

- source/MaterialProperty.cc
- source/MaterialProperty.hh
- source/ScanPath.cc
Fix warnings when compiling with clang
> Fix warnings

- ci/jenkins_config
- source/MaterialProperty.cc
- source/ThermalOperator.cc
- source/ThermalPhysics.templates.hh
- tests/CMakeLists.txt
- tests/test_thermal_physics.hh
This is a hot fix for MPI simulation. I plan to add a MPI+CUDA test and probably add a sanitizer test. I spent hours finding a bug in the previous PR that I fixed in 10 minutes using the sanitizer. To review the PR, use the option to hide white space differences. I have a changed an if condition and the indentation is different.
> Fix bug when using MPI

- doc/adamantine.tex
I messed up when I tried to push the changes on the branch and instead I deleted the remote branch and it closed #102 The PR is the same than #102 but I have applying your suggestions.
> Update latex documentation

- README.md
- application/adamantine.hh
- source/ScanPath.cc
A few different fixes and added options for mixing AMR with adding material
> AMR + Material Deposition

- application/adamantine.hh
- source/CMakeLists.txt
- source/MaterialProperty.cu
- source/MaterialProperty.hh
- source/MaterialProperty.templates.hh
- source/Physics.hh
- source/ThermalOperator.cc
- source/ThermalOperator.hh
- source/ThermalOperatorBase.hh
- source/ThermalOperatorDevice.hh
- source/ThermalPhysics.hh
- source/ThermalPhysics.templates.hh
- source/material_deposition.cc
- source/material_deposition.hh
- tests/test_implicit_operator.cc
- tests/test_material_deposition.cc
- tests/test_post_processor.cc
- tests/test_thermal_operator.cc
- tests/test_thermal_operator_device.cu
- tests/test_thermal_physics.cc
- tests/test_thermal_physics.hh
This PR superseeds #91 and #107
It is very similar to #91 but the CUDA code is left untouched and we need to deal with the convective and radiative boundary conditions. Right now, these are not treated in a matrix-free way. This is pretty slow but to fix this, we need some changes in deal.II
> Compute the material properties at each quadrature point

- README.md
- application/adamantine.cc
- application/adamantine.cu
- ci/jenkins_config
- source/CMakeLists.txt
- source/MaterialProperty.templates.hh
- source/ThermalPhysics.templates.hh
- source/material_deposition.cc
- source/types.hh
- source/validate_input_database.cc
- source/validate_input_database.hh
- tests/CMakeLists.txt
- tests/data/demo_316_short.info
- tests/test_validate_input_database.cc
This adds a check to validate the input file at the start of the simulation. Most of the input checks in the code have been moved here, with a few exceptions. In cases where there is a defined list of options, the core part of the code still has some `else` statements with thrown exception if input doesn't match the options. I think this helps the readability of the code and doesn't add much complexity. The other case is when the validation is intricately tied to the parsing (e.g. checking for the experimental camera files). At least at this point, I didn't want to have to repeat too much of the logic/parsing process in two places.
To test the input validation, I tried to balance coverage, length, and my time. It isn't exhaustive (e.g. I don't consider all possible combinations of valid …
> Verify input file

- source/DataAssimilator.cc
deal.II is missing some wrappers for ArborX. There is a bunch of code that will move there in the future. Once that's done and we update deal.II in the CI, I will remove the code in adamantine
> Use ArborX to speedup localization

- .github/workflows/Dockerfile
- .github/workflows/docker.yml
- source/Operator.hh
With this PR every merge on master should build and deploy a new Docker image where adamantine is installed.This is the CPU only version of the code. The only way to know if it works is to merge the PR :/
> Deploy Docker image on push on master

- source/MemoryBlock.hh
- source/MemoryBlockView.hh
- source/ThermalOperator.cc
- tests/test_thermal_operator.cc
This PR contains small fixes that I have extracted from my work refactoring `ThermalOperatorDevice`.
> Small fixes

- .clang-format
- ci/Dockerfile
This a first of few patches that add elastostacity to adamantine. I will not add the documentation about how to use mechanical right away because I am not satisfied with the current state.
> Update deal.II and dealii-weak_forms in Docker image

- source/MechanicalOperator.cc
- source/MechanicalOperator.hh
- source/MechanicalPhysics.cc
- source/MechanicalPhysics.hh
- tests/test_mechanical_operator.cc
- tests/test_mechanical_physics.cc
Add a test using the analytic Eshelby solution and make some minor fixes to MechanicalOperator and MechanicalPhysics.
> Add analytic solution test for thermoelasticity

- application/adamantine.hh
- source/CubeHeatSource.cc
- source/CubeHeatSource.hh
- source/ElectronBeamHeatSource.cc
- source/ElectronBeamHeatSource.hh
- source/GoldakHeatSource.cc
- source/GoldakHeatSource.hh
- source/HeatSource.hh
- source/ThermalOperator.cc
- source/ThermalOperator.hh
- source/ThermalPhysics.templates.hh
- tests/test_heat_source.cc
By having a function `update_time`, we don't have to recompute everything at each quadrature point.
> Do not recompute the same quantities several times over in the heat sources

- application/adamantine.hh
- source/MaterialProperty.hh
- source/MaterialProperty.templates.hh
- source/MechanicalOperator.cc
- source/MechanicalOperator.hh
- source/types.hh
- tests/test_mechanical_physics.cc
This PR replaces the dummy body force by the gravity. I've also move some code around to silence a warning.
[CI](https://cloud.cees.ornl.gov/jenkins-ci/blue/organizations/jenkins/adamantine/detail/adamantine/295/pipeline)
> Replace dummy force by gravity

- ci/Dockerfile
- ci/jenkins_config
- cmake/SetupTPLs.cmake
- source/DataAssimilator.cc
- source/MaterialProperty.templates.hh
- source/MechanicalOperator.cc
- source/ScanPath.cc
- source/ThermalOperatorDevice.cu
- source/ThermalPhysics.templates.hh
- source/material_deposition.cc
- source/types.hh
- source/validate_input_database.cc
- tests/test_implicit_operator.cc
- tests/test_thermal_operator.cc
- tests/test_thermal_operator_device.cu
No ready for review/to be merged. Just testing the CI
> Update Docker image

- source/DataAssimilator.cc
- tests/test_data_assimilator.cc
- tests/test_integration_da_augmented.cc
Small improvements in data assimilation to make the code and the tests more robust. Also remove a test that was duplicated.
> Data assimilation improvements

- application/adamantine.hh
- ci/jenkins_config
- source/CMakeLists.txt
- source/MechanicalOperator.cc
- source/MechanicalOperator.hh
- source/MechanicalPhysics.cc
- source/MechanicalPhysics.hh
- source/MechanicalPhysicsDummy.hh
- source/PostProcessor.cc
- source/ThermalPhysics.hh
- source/ThermalPhysics.templates.hh
- source/ThermalPhysicsInterface.hh
- source/validate_input_database.cc
- tests/CMakeLists.txt
- tests/data/thermoelastic_bare_plate.info
- tests/data/thermoelastic_bare_plate_scan_path.txt
- tests/test_integration_thermoelastic.cc
- tests/test_material_deposition.cc
- tests/test_mechanical_operator.cc
- tests/test_mechanical_physics.cc
- tests/test_post_processor.cc
- tests/test_thermal_physics.cc
- tests/test_thermal_physics.hh
- tests/test_validate_input_database.cc
This PR does the following things:
- Adds a new state that tracks if the cell has been melted
- Adds functionality to adjust the state if the cell goes above a certain temperature
- Changes the thermal expansion to be vs a reference temperature that depends on whether the cell has melted
- Tests
> Thermoelasticity with reference temperatures

- source/MechanicalOperator.cc
- tests/test_integration_thermoelastic.cc
[CI](https://cloud.cees.ornl.gov/jenkins-ci/blue/organizations/jenkins/adamantine/detail/adamantine/361/pipeline)
> Fix a bug when using FE_Nothing for thermo-mechanical problem

- source/experimental_data.cc
This is another step toward supporting DA in parallel. [CI](https://cloud.cees.ornl.gov/jenkins-ci/blue/organizations/jenkins/adamantine/detail/adamantine/371/pipeline)
> Use DistributedTree in get_expt_to_dof_mapping

- source/RayTracing.cc
@stvdwtt can you try this PR and tell me if it fixes the problem in #225
[CI](https://cloud.cees.ornl.gov/jenkins-ci/blue/organizations/jenkins/adamantine/detail/adamantine/374/pipeline)
> Refactor Raytracing

- ci/jenkins_config
- source/MechanicalOperator.cc
- source/ThermalPhysics.hh
- source/ThermalPhysics.templates.hh
- source/ThermalPhysicsInterface.hh
Fixes #186
[CI](https://cloud.cees.ornl.gov/jenkins-ci/blue/organizations/jenkins/adamantine/detail/adamantine/378/pipeline/)
> Fix bugs when running mechanical simulation with MPI

- application/adamantine.hh
- source/DataAssimilator.cc
- source/DataAssimilator.hh
- source/experimental_data_utils.cc
- tests/test_data_assimilator.cc
[CI](https://cloud.cees.ornl.gov/jenkins-ci/blue/organizations/jenkins/adamantine/detail/adamantine/385/pipeline)
> Small improvements for DA

- application/adamantine.hh
- source/PostProcessor.cc
- source/PostProcessor.hh
- tests/test_post_processor.cc
[CI](https://cloud.cees.ornl.gov/jenkins-ci/blue/organizations/jenkins/adamantine/detail/adamantine/397/pipeline)
> Fix risk of overflow in PostProcessor

- source/validate_input_database.cc
- tests/test_validate_input_database.cc
[CI](https://cloud.cees.ornl.gov/jenkins-ci/blue/organizations/jenkins/adamantine/detail/adamantine/396/pipeline)
> Fix input validation when using a third-party mesh

- source/Geometry.cc
[CI](https://cloud.cees.ornl.gov/jenkins-ci/blue/organizations/jenkins/adamantine/detail/adamantine/394/pipeline)
> Fix loading mesh from third party

- application/adamantine.hh
This PR fixes #247 The way the code was working was the following: we compute all the cells that are activated as part of the material deposition and we associate a time stamp them. Then we need to add material, we search for the cells that need to be activated given their time stamp. When the mesh is refine, we recompute the new cells to activate. The issue is that adding material triggers a mesh repartitioning and the cells that needed to be activated may have moved to a different processor. In debug mode this causes the code to crash because we are not allowed to activate a cell that is not locally owned. In release mode, the code keeps running but the cells are not activated anymore. The solution is to recompute the cells to activate every time that we want to add material.
> Fix a bug when depositin material in parallel

- source/BodyForce.cc
- source/BodyForce.hh
- source/CMakeLists.txt
- source/MechanicalOperator.cc
- source/MechanicalOperator.hh
- source/MechanicalPhysics.cc
- source/MechanicalPhysics.hh
- tests/test_mechanical_operator.cc
- tests/test_mechanical_physics.cc
This is a generalization of the gravity body force. The goal is to simplify testing of the plastic simulation. [CI](https://cloud.cees.ornl.gov/jenkins-ci/blue/organizations/jenkins/adamantine/detail/adamantine/408/pipeline)
> Add support for general body forces

- README.md
- application/adamantine.hh
With this PR we can add more materials at once. I choose a deposition time parameter but we can pick something else. I don't know what's easier to use. One thing we need to be careful about is that our source term currently does not support multiple layers at the same time. So if we add too much material at the end of the layer the source term will be wrong.
[CI](https://cloud.cees.ornl.gov/jenkins-ci/blue/organizations/jenkins/adamantine/detail/adamantine/390/pipeline)
> Add lumps of material during deposition

- ci/jenkins_config
There have been some changes on the Jenkins configuration. Options that used to be defined on the server side, now need to be defined in the configuration file.
> Update jenkins configuration file for Multibranch pipeline

- application/adamantine.cc
- application/adamantine.hh
- tests/test_integration_2d.cc
- tests/test_integration_2d_device.cc
- tests/test_integration_3d.cc
- tests/test_integration_3d_amr.cc
- tests/test_integration_3d_amr_device.cc
- tests/test_integration_3d_device.cc
- tests/test_integration_da.cc
- tests/test_integration_da_augmented.cc
- tests/test_integration_thermoelastic.cc
With this PR, we can read input files that use the `json` format. It's easier to manipulate `json` file than `info` file in python so it should make your life easier @stvdwtt
> Add json reader

- .github/workflows/Dockerfile
- application/adamantine.hh
- source/ThermalOperatorDevice.cc
- source/ThermalPhysics.cc
- source/instantiation.hh
- source/validate_input_database.cc
I am going to introduce a few more template parameters, so let's reduce the number of instantiations before I do that. This PR also adds the `-ffast-math` flag when compiling the `adamantine` binary in the Docker image.
> Reduce max FE degree from 10 to 5

- joss/paper.bib
- joss/paper.md
@stvdwtt Here is the draft of the JOSS paper. We can either iterate on the PR or work on the branch directly. It's up to you. Here are the requirements for the paper: https://joss.readthedocs.io/en/latest/paper.html
> Draft JOSS paper

- source/MaterialProperty.templates.hh
- source/MechanicalOperator.cc
- source/MechanicalPhysics.cc
- source/PostProcessor.cc
- source/experimental_data_utils.cc
It's not obvious what the second argument in `ActiveFEIndexEqualTo` is for so add a comment explaining that we want only locally owned cells.
> Be explicit about the second argument of ActiveFEIndexEqualTo

- application/adamantine.hh
Previously the simulation would crash if there were no intersections.
Note, the changes are very modest except for whitespace.
> Skip DA if no expt points map to DOF

- tests/data/HourGlass_AOP.info
This is part of the rework of the HourGlass example. See the discussion on the website: https://adamantine-sim.github.io/adamantine/doc/examples/hour_glass.html
> Add caliper configuration command to HourGlass_AOP.info

- tests/data/bare_plate_L_da_augmented.info
- tests/data/bare_plate_L_ensemble.info
The input file is currently used in the input validation test but I want to use it for the data assimilation examples. To do that I need to make this change.
> Increase initial_temperature_stddev in bare_plate_L_ensemble.info

- source/MechanicalPhysics.cc
@stvdwtt Can you test this PR.
> Fix setup of plastic variables

- flake.nix
Nix by default strips the symbols required for debugging. This change builds Adamantine with the debug symbols and gdb. Launch with
$ nix develop .#debug
See
- https://nixos.org/manual/nixpkgs/stable/#stdenv-separateDebugInfo
- https://rski.github.io/2021/09/05/nix-debugging.html
> Add debug environment to nix build

- application/adamantine.cc
Fixes https://github.com/adamantine-sim/adamantine/issues/348 See the explanation [here](https://github.com/adamantine-sim/adamantine/issues/348#issuecomment-2524138514).
> Fix a bug when detecting the number of material states

- application/adamantine.hh
Make the output on the screen more uniform when using `verbose_output`
> Improve output on screen

- application/adamantine.hh
Currently we are giving the global communicator to the IR data `PostProcessor` but we should use a local communicator. More over not all processors need to write the data, only those associated with member zero.
> Use local_communicator for IR data PostProcessor

- .github/workflows/Dockerfile
Add `-g` to the Docker image to improve debugging
> Add -g flag to the Docker image built by github

- CMakePresets.json
- flake.nix
Modified flake.nix and CMakePresets.txt files to have an clang build option for mac compilation
> Clang option for build

- source/ThermalPhysics.templates.hh
The `_has_melted` flag is not used in thermal simulation and so it was missing from the checkpoint/restart data. However, we do project the flag when refining the mesh/adding materials. Even  though the value of `_has_melted` is not important, it is important for the `std::vector`  to have the right size. This PR add the `_has_melted` flag to fix that issue.
> Add missing has_melted flag to the checkpoint/restart
