adamantine-sim/adamantine

CMakeLists.txt, application/CMakeLists.txt, ci/Dockerfile, cmake/SetupTPLs.cmake, cmake/Testing.cmake, source/CMakeLists.txt, source/MaterialProperty.cc, source/MaterialProperty.hh, source/ThermalOperator.cc, source/ThermalOperator.hh, source/ThermalOperatorBase.hh, source/ThermalOperatorDevice.cu, source/ThermalOperatorDevice.hh, source/ThermalPhysics.hh, source/ThermalPhysics.templates.hh, tests/test_implicit_operator.cc, tests/test_post_processor.cc, tests/test_thermal_operator.cc, tests/test_thermal_operator_device.cu, tests/test_thermal_physics.hh
This PR does the following:
- Update the code to work with a newer version of deal.II: once this is merged everybody will need to update deal.II.
- Update the build system: in particular require a newer version of CMake and bump the C++ standard to C++17. This will allow us to use the parallel capabilities of the STL library.
- Use hp::FECollection everywhere this is needed for element activation.
=> Element activation

application/adamantine.hh, source/CubeHeatSource.cc, source/CubeHeatSource.hh, source/ElectronBeamHeatSource.cc, source/ElectronBeamHeatSource.hh, source/Geometry.cc, source/Geometry.hh, source/GoldakHeatSource.cc, source/GoldakHeatSource.hh, source/HeatSource.hh, source/ThermalPhysics.hh, source/ThermalPhysics.templates.hh, tests/test_heat_source.cc
This allows the heat sources to adapt to the addition of material. This is PR uses a single new height. This is sufficient for now and I am not sure that we are interested in cases where the new height is different in different part of the domain. That would mean that we start building part of the object and then go back down to finish another part.
=> Recompute the max height of the object during the simulation

source/ElectronBeamHeatSource.cc, source/Geometry.cc, source/GoldakHeatSource.cc, source/types.hh, tests/test_geometry.cc, tests/test_heat_source.cc
The element activation code has many moving parts so instead of having one big PR, I will create a bunch of small ones. This PR fixes the problem where the y and z are switched in 3D
=> Create map between x, y, and z axes and 0, 1, and 2 indices

source/ThermalPhysics.templates.hh, tests/CMakeLists.txt, tests/test_material_deposition.cc
Transferring solution when adding material is a little bit tricky. First, I forgot to update the ghost value. Second to use `CellDataTransfer`, we need data on every active including non-locally owned. So we need to be very careful on which operation is done on locally owned cells and which operation is done on active cells.
=> Fix bugs when using more than one MPI rank

cmake/Setupadamantine.cmake, source/utils.hh
I had a plan to use a more advanced `assert` from boost but I don't think that's worth the effort. Instead, let's just use `cassert` this slightly simplifies the build system.
=> Replace Boost assert with cassert

source/ScanPath.cc, tests/test_heat_source.cc, tests/test_scan_path.cc
When the simulation reaches the end of a scan path file, the heat source power is now set to zero and its position is the last position from the scan path file. Previously there could be unexpected behavior.
=> improve scan path robustness

README.md, application/input.info, source/MaterialProperty.cc, source/MaterialProperty.hh, source/ThermalOperator.cc, source/ThermalOperator.hh, source/ThermalPhysics.hh, source/ThermalPhysics.templates.hh, source/types.hh, tests/data/integration_2d.info, tests/test_implicit_operator.cc, tests/test_material_deposition.cc, tests/test_post_processor.cc, tests/test_thermal_operator.cc, tests/test_thermal_operator_device.cu, tests/test_thermal_physics.hh
This adds support for radiative and convective boundary condition. I had to treat the boundary outside the MatrixFree framework because of the element activation. We are still deciding how we will treat that case in deal.II
=> Add radiative and convective boundary conditions

application/adamantine.hh, source/material_deposition.cc, source/types.hh
There were a few sign errors in the code to determine the material to add from the scan path. I also split the add material timers into to (one to decide which material to add, one to actual activate it).
=> Fix bug when adding material based on the scan path

source/ArrayMD.hh, source/CMakeLists.txt, source/ThermalPhysics.templates.hh, source/utils.hh, tests/CMakeLists.txt, tests/test_arraymd.cc, tests/test_arraymd_device.cu, tests/test_thermal_operator_device.cu
This PR adds new data structures: `Array2D`, `Array3D,` `Array4D`, and `Array5D` The memory space where the data is stored is determined by the last template parameters `MemorySpaceType`. The dimensions of the `Array` can be set at compile time using a template parameter or at run-time. In that last case, the template parameter should be set to `-1`. Note that I didn't implement all the combinations of compile/run-time parameters. I've implemented the one that I use in other parts of the code.
=> Add array for CPU and GPU

.clang-format, README.md, application/CMakeLists.txt, application/adamantine.cc, application/adamantine.cu, application/adamantine.hh, ci/Dockerfile, cmake/SetupTPLs.cmake, source/ThermalPhysics.templates.hh, tests/CMakeLists.txt, tests/data/demo_316_short.info
This adds support for [adiak](https://github.com/LLNL/Adiak). Adiak is necessary for Caliper to write data can be read by [spot](https://github.com/LLNL/spotfe/). My plan is to monitor the performance on the host using `demo_316_short`. Once I have a better understanding of spot, I may add more test cases.
=> Add support for adiak

source/MaterialProperty.hh, source/MaterialProperty.templates.hh, source/ThermalOperator.cc, source/ThermalOperatorDevice.cu, source/ThermalPhysics.templates.hh, tests/test_material_property.cc
=> Rename MaterialProperty::get to MaterialProperty::get_cell_value when using a cell

README.md, source/ScanPath.cc, source/ScanPath.hh, tests/data/demo_316_short_scan_path.txt, tests/data/scan_path_layers.txt
- Fix the READMS
- Fix scan path input files
- Read number of segments of the scan path (this easier to read if you use `Hide Widespace`). We know stop reading the file when the file ends or we reached the maximum number of segments to read, whichever comes first.
- Support `csv` format for event scan path
=> Small fixes

source/material_deposition.cc, source/material_deposition.hh, tests/test_material_deposition.cc, tests/test_material_property.hh
This merges multiple deposition paths into a single one. We had that for quite a while but it was actually quite simple to implement: we split the deposition into bounding boxes, sort the bounding boxes by the time of depositions, and finally reassemble the vector.
=> Merge multiple deposition paths

source/DataAssimilator.cc, source/DataAssimilator.hh, tests/test_data_assimilator.cc
This removes one of the places where full matrices are used for data assimilation. The diagonal R case is the only case currently supported by the adamantine application, but we still have the non-diagonal case available as a more general fall-back.
=> No full matrices in DataAssimilator for the random number fill for diagonal R

README.md, ci/Dockerfile, source/ensemble_management.cc
I was trying to add a new test case but I hit the multithreading bug https://github.com/adamantine-sim/adamantine/issues/130 This PR updates the Docker image and the README
=> Disable multithreading in Docker image and update README

tests/data/demo_316_short.info
The `demo_316_short.info` input file was missing the entries necessary for convective and radiative BCs and therefore the calculation went to all NANs.
Currently we don't have any notification if the user selects convective or radiative BCs but doesn't give the expected input parameters for those BC models. Part of this is how things are currently split up -- ThermalOperator handles the BCs but doesn't have access to the input material database and MaterialProperty handles the material properties but doesn't have access to the BC type. One option would be to have a check in ThermalPhysics to see if things are appropriately defined (ThermalPhysics currently gets the whole input database). Another option would be to have something in MaterialProperty that tracks what is defined and what …
=> Add missing BC inputs in the 316 demo input file

application/adamantine.hh, source/ThermalOperator.cc, tests/data/bare_plate_L_da.info
This PR makes several changes to ensemble calculations, mostly relating to AMR:
- It resizes the blocks appropriately for the solution vector when the number of DOFs change
- It removes the copy of the constraints in `run_ensemble`, changing to direct access from `ThermalPhysics` to prevent the constraints from being out of sync
- It applies the constraints before data assimilation
- For AMR generally, it changes how the beam intensity is checked, adding checks at face centers
- For augmented state data assimilation, it prints out the augmented parameters before and after each data assimilation operation
- AMR is added to the data assimilation integration test
=> AMR fixes for ensemble calculations

tests/test_data_assimilator.cc, tests/test_ensemble_management.cc, tests/test_experimental_data.cc, tests/test_geometry.cc, tests/test_heat_source.cc, tests/test_implicit_operator.cc, tests/test_integration_2d.cc, tests/test_integration_2d_device.cu, tests/test_integration_3d.cc, tests/test_integration_3d_amr.cc, tests/test_integration_da.cc, tests/test_integration_da_augmented.cc, tests/test_material_deposition.cc, tests/test_material_property.hh, tests/test_mechanical_operator.cc, tests/test_newton_solver.cc, tests/test_post_processor.cc, tests/test_scan_path.cc, tests/test_thermal_operator.cc, tests/test_thermal_operator_device.cu, tests/test_thermal_physics.hh
`BOOST_TEST` is the modern version of `BOOST_CHECK`. It has extra capabilities and most importantly the error message is better. I didn't use it before because there was a problem with CUDA but it is supposed to be fixed. I made the change on a computer without a GPU so let's see if the CI passes.
=> Replace BOOST_CHECK with BOOST_TEST

application/adamantine.hh, source/PostProcessor.cc, source/PostProcessor.hh, tests/test_integration_2d.cc, tests/test_post_processor.cc
Refactor `PostProcessor`  to be able to output thermal results, mechanical results, or thermo-mechanical results. For now, the mechanical output is limited to displacement and strain. Adding stress is not difficult but it requires to also pass the `MaterialProperty`. I've let that for later.
=> Refactor PostProcessor to output result of mechanical simulation

application/adamantine.hh, source/MaterialProperty.hh, source/MaterialProperty.templates.hh, source/MechanicalOperator.cc, source/MechanicalOperator.hh, source/MechanicalPhysics.cc, source/MechanicalPhysics.hh, source/Physics.hh, source/ThermalOperator.cc, source/ThermalOperator.hh, source/ThermalOperatorDevice.cu, source/ThermalOperatorDevice.hh, source/ThermalPhysics.hh, source/ThermalPhysics.templates.hh, source/types.hh, tests/test_implicit_operator.cc, tests/test_material_deposition.cc, tests/test_material_property.hh, tests/test_mechanical_operator.cc, tests/test_mechanical_physics.cc, tests/test_post_processor.cc, tests/test_thermal_operator.cc, tests/test_thermal_operator_device.cu, tests/test_thermal_physics.hh
This PR does two things:
- Move `MaterialProperty` out of `ThermalPhysics` since we also need it in `MechanicalPhysics`
- Add support for mechanical properties in `MaterialProperty`. Unlike thermal properties, mechanical properties only exist on the host so we cannot simply extend the current data structure to accommodate the mechanical properties. Instead part of the data structures needs to be duplicated.
=> Add support for mechanical properties in MaterialProperty

application/adamantine.cc, application/adamantine.hh
The text for the timer for reading in experimental data was added twice to the `timers` vector. This lead to incorrect matching between the timer text and the timer counters.
I also changed the simulation start notification to say whether it is an ensemble simulation or not.
=> Fix timer print-out text

.github/workflows/Dockerfile
- Adding `dealii-weak_forms` to the docker image that we produce on merge to allow people to use the mechanical simulation.
- Adding Caliper and Adiak, so user can send us a `cali` file to know why the code is slow.
=> Add Caliper, Adiak, and dealii-weak_forms to the adamantine docker image

source/ThermalOperator.cc, source/ThermalOperator.hh, source/ThermalOperatorBase.hh, source/ThermalOperatorDevice.cu, source/ThermalOperatorDevice.hh, source/ThermalPhysics.templates.hh, tests/test_implicit_operator.cc, tests/test_post_processor.cc, tests/test_thermal_operator.cc, tests/test_thermal_operator_device.cu
With this PR, computing the inverse of the mass matrix is negligible. Now when adding material, most of the time is spent in p4est.
Related to #172 
[CI](https://cloud.cees.ornl.gov/jenkins-ci/blue/organizations/jenkins/adamantine/detail/adamantine/294/pipeline)
=> Use MatrixFree framework to compute the inverse of the mass matrix

source/MaterialProperty.hh, source/MaterialProperty.templates.hh, source/ThermalOperator.cc, source/ThermalOperator.hh
When using `adiabatic` boundary condition, the majority of the time is spent computing the powers of the temperature in order to evaluate material properties. Instead of computing the powers every time we need to get a material property, we compute them once and give them to `MaterialProperty`. While this improves performance a lot, computing the powers of the temperature is still the most expensive part of performing one time step.
Related to #172
[CI](https://cloud.cees.ornl.gov/jenkins-ci/blue/organizations/jenkins/adamantine/detail/adamantine/300/pipeline)
=> Move computation of temperature powers out of MaterialProperty 

source/MaterialProperty.templates.hh, source/ThermalOperatorDevice.cu, source/ThermalPhysics.templates.hh, tests/CMakeLists.txt, tests/test_integration_3d_device.cu
After this PR is merged, AMR will be the only capability missing on GPU. Some of these capabilities are actually run on the CPU but hopefully we can move them on the GPU later on.
[ci](https://cloud.cees.ornl.gov/jenkins-ci/blue/organizations/jenkins/adamantine/detail/adamantine/327/pipeline)
=> Add support for material addition when using GPU.

application/adamantine.hh, source/MaterialProperty.hh, source/MaterialProperty.templates.hh, source/ThermalOperator.cc, source/ThermalOperatorDevice.cu, source/ThermalPhysics.templates.hh
With this PR, the compiler removes the call to `pow`. Now the execution time is dominated by adding material and refining the mesh.
=> Make polynomial_order and table_size constexpr

tests/CMakeLists.txt, tests/test_integration_3d_amr_device.cu
For the longest time I thought that AMR did not work with GPU but apparently it does. It looks like the GPU has now the same capabilities as the CPU backend. The only thing left to do is to profile it and fix the bottlenecks.
[CI](https://cloud.cees.ornl.gov/jenkins-ci/blue/organizations/jenkins/adamantine/detail/adamantine/342/pipeline)
=> Add AMR test on the GPU

tests/data/thermoelastic_bare_plate.info
User cannot set the quadrature type for the mechanical simulation. The reason it is allowed for the thermal simulation is that it simplifies a lot the computation of the inverse of the mass matrix (it is a diagonal matrix with the `lobatto` quadrature) which is interesting for explicit time-stepping.
[CI](https://cloud.cees.ornl.gov/jenkins-ci/blue/organizations/jenkins/adamantine/detail/adamantine/345/pipeline)
=> Remove unused variable in input file

source/experimental_data.cc, tests/test_experimental_data.cc
There is no reason to loop over the ghost cells. On top of that the current code does not work on the MPI case with artificial cell because you cannot check the fe index on an artificial cell. One test needs to be changed because it won't pass with two processors anymore. However, it was passing just by chance. We have one processor that owns the four cells on the bottom of the domain and one processor that owns the four cells on the top and so the ghost + locally owned cells represent the entire mesh. So we are basically solving the same problem as the serial one.
=> Only loop over locally owned cells in get_dof_to_support_mapping

source/ThermalPhysics.templates.hh
This is a small clean up. It doesn't make a different in this case but it's the correct way to do. [CI](https://cloud.cees.ornl.gov/jenkins-ci/blue/organizations/jenkins/adamantine/detail/adamantine/376/pipeline)
=> Use set_future_fe_index instead of set_active_fe_index before refining the mesh

application/adamantine.hh, source/MaterialProperty.hh, source/MaterialProperty.templates.hh, source/ThermalOperator.cc, source/types.hh
There are many places where we need to know things like `n_material_states`. Right now every time  we want to loop over the number of material states, we need to cast the `enum` to `unsigned int`. Instead this PR defines global variables that do the casting and that we can reuse through the code.
[CI](https://cloud.cees.ornl.gov/jenkins-ci/blue/organizations/jenkins/adamantine/detail/adamantine/399/pipeline)
=> Simplify code using global variables

README.md, source/validate_input_database.cc, tests/data/bare_plate_L_da.info, tests/data/bare_plate_L_da_augmented.info, tests/data/integration_da_add_material.info, tests/test_validate_input_database.cc
We removed `data_columns` a while back we forgot to remove it from the tests and from the input validation [CI](https://cloud.cees.ornl.gov/jenkins-ci/blue/organizations/jenkins/adamantine/detail/adamantine/405/pipeline)
=> Remove remnant of data_columns

application/adamantine.hh, source/MaterialProperty.hh, source/MaterialProperty.templates.hh, source/MechanicalPhysics.cc, source/MechanicalPhysics.hh, source/PostProcessor.cc, source/PostProcessor.hh, source/RayTracing.cc, source/types.hh, tests/test_mechanical_physics.cc, tests/test_post_processor.cc
This is still a work in progress. The first two commits could be moved to their own PRs but they are literally one line each so I don't think it matters.
Things left to do:
- Decide where the new code should go. I've put it in `MechanicalPhysics` but we could put it in `MechanicalOperator`. My reasoning is that, the new code does not need "solving" but I don't know where is the right place.
- The code does not work if the mesh is refined or material is added.
- Testing. I tried to find analytical solutions on internet but I couldn't find anything. Usually people just do comparisons with commercial software but the models are slightly different and the results don't match. If I could get help with that, it would be fantastic.
=> Add support for J2 plasticity 

application/adamantine.hh, source/DataAssimilator.cc, source/DataAssimilator.hh, source/ensemble_management.cc, source/ensemble_management.hh, tests/CMakeLists.txt, tests/test_data_assimilator.cc, tests/test_ensemble_management.cc, tests/test_integration_2d.cc, tests/test_integration_da.cc, tests/test_integration_da_augmented.cc
With this PR, we can finally run data assimilation in parallel. We can use up to as many processors as there are ensemble members. The way this is done is by splitting the global MPI communicator (we use MPI_COMM_WORLD) in multiple local communicators and then using these local communicators where needed. A lot of the PR is just about choosing the right communicator. The data assimilation itself is still done in serial on rank 0. This means that all the vectors need to be move to the rank 0 and out of it after they have been updated. There are two difficulties with this operation: 
1. there is no facility in deal.II to move an entire vector to a single processor and so we have to ship the data and rebuild the vector by hand
2. the algorithm is more complicated than it should be because I …
=> Use MPI groups to parallelize data assimilation

application/adamantine.hh
We use an epsilon to get the "expected" behavior when the deposition time and the time match should match exactly but don't because of floating point accuracy. I changed eps to be computed using the deposition start time and error between the time step and activation time.
=> Changed eps in timestepping 

ci/Dockerfile, ci/jenkins_config
I quickly tried to get clang back in the CI but it doesn't work. We need to build a new image that uses clang for Trilinos and deal.II. I am not convinced that it's something we want to do.  On my personal machine, I use HIP and therefore clang and everything works fine.
=> Remove clang related code in the CI

source/DataAssimilator.cc, source/MechanicalOperator.cc, source/Timer.cc
I ran clang-tidy a couple of months ago and forgot to push the changes. There is nothing really important. Here is the clang-tidy options that I have used:
```
Checks: >
-*,
bugprone-too-small-loop-variable,
bugprone-unchecked-optional-access,
bugprone-use-after-move,
bugprone-virtual-near-miss,
cppcoreguidelines-init-variables,
modernize-deprecated-headers,
modernize-use-nullptr,
modernize-use-override,
modernize-use-using,
mpi-*
performance-*,
-performance-inefficient-string-concatenation,
-performance-avoid-endl
```
=> Fix clang-tidy warnings

source/ThermalPhysics.templates.hh
When adding material, we need to keep track of the cell ids of the activated cells, the locally owned cells, and the active cells. There is a bug in the current code.
=> Fix bug when adding material

README.md, application/adamantine.hh, source/MaterialProperty.hh, source/MaterialProperty.templates.hh, source/ThermalPhysics.hh, source/ThermalPhysics.templates.hh, source/ThermalPhysicsInterface.hh, tests/test_integration_3d.cc, tests/test_integration_3d_device.cc, tests/test_material_deposition.cc, tests/test_mechanical_physics.cc, tests/test_thermal_physics.hh
This PR adds support for checkpoint/restart.  deal.II uses SolutionTransfer for the serialization and so, the new code is very similar to the code to transfer data when the mesh is refined. I haven't tested the case where the chekpoint and the restart use different number of processors but when testing with more than 1 processor, the partitioning is different. This is because when we first create a mesh we use a cell-based partitioning whereas after the first refinement we use a dof-based partitioning. This gives me some confidence that it works as expected. Note that deal.II creates several files during serialization and that I also create a file to store the current time step number and the current time.
=> Add support for checkpoint/restart

source/MaterialProperty.hh, source/MaterialProperty.templates.hh, source/ThermalOperator.cc, source/ThermalOperator.hh, source/ThermalOperatorDevice.cc, source/ThermalOperatorDevice.hh, source/ThermalPhysics.templates.hh, source/instantiation.hh, tests/test_implicit_operator.cc, tests/test_post_processor.cc, tests/test_thermal_operator.cc, tests/test_thermal_operator_device.cc
Use `if constexpr (use_table)` in `compute_material_property`. This gives us a noticeable speed up. I didn't template all of `MaterialProperty` on `use_table` because the other functions don't show up in the profiling and this keeps the code easier.
=> Make use_table a template parameter in hot loops

README.md, source/Geometry.cc, source/validate_input_database.cc, tests/test_geometry.cc
This is the first of two PRs to let us do the curved wall build for the Okuma. This one is focused on relaxing the assumption that the entire domain is in the +x, +y, +z octant. A common AM reference frame has the top of the substrate centered at (0, 0, 0).
Changes:
- Removes the check that the material height must be positive
- Allows the user to specify the origin for an adamantine-generated meshes
- Allows user-defined scaling of a read-in mesh
- Allows the material id of a read-in mesh be cleared and set to 0
=> Increase flexibility in creating meshes and loading meshes

source/ThermalPhysics.templates.hh
I wrote the code with clang and didn't get any warning but GCC is not happy.  Adding more braces should fix the issue.
=> Fix GCC warning

application/adamantine.hh, ci/jenkins_config, source/DataAssimilator.cc, source/RayTracing.cc, source/experimental_data_utils.cc, tests/CMakeLists.txt
This PR enables us to use multiple processors per ensemble member. This only works if the all the ensemble members use the same number of processors. This ensures that the mesh is partitioned the same way for all the ensemble members which simplifies some operations. We could remove this condition in the future.
The changes in the code are pretty small if you hide the whitespace changes. Most of the bugs were related to some data not being distributed to all the processors.
=> Add support to using more than one MPI rank per ensemble member

README.md, application/adamantine.hh, application/input.info, source/ThermalPhysics.hh, source/ThermalPhysics.templates.hh, source/ThermalPhysicsInterface.hh, source/validate_input_database.cc, tests/data/amr_test.info, tests/data/bare_plate_L_da.info, tests/data/bare_plate_L_da_augmented.info, tests/data/bare_plate_L_ensemble.info, tests/data/demo_316_short.info, tests/data/demo_316_short_anisotropic.info, tests/data/integration_2d.info, tests/data/integration_2d_ensemble.info, tests/data/integration_da_add_material.info, tests/data/thermoelastic_bare_plate.info
This is the last PR I would like to get merged before creating the release branch. This removes the embedded time stepping methods (aka the adaptive time step method) and the AMR based on the Kelly estimator. We are not using either of these capabilities and they are making the code and the input file more complicated. The embedded method methods are problematic for the GPU computations and the Kelly estimator AMR is not usable in practice because the number of cells cannot be kept stable. We may reintroduce these capabilities in the future but we need to do it in a more thoughtful way.
=> Remove embedded time stepping methods and Kelly estimator AMR

CMakeLists.txt
I've just created the branch for the `1.0`. Let's bump the version on master to `1.0.9` (this is inspired by what Kokkos does where the current development version is `4.3.99`)
=> Bump version to 1.0.9 on master

tests/main.cc
`feenableexcept` doesn't exist on MacOS X.
=> Fix compiling tests with MacOS X

source/experimental_data_utils.cc, source/material_deposition.cc
Trying to compile with `clang++`, I am running into a bunch of missing explicit instantiations that this pull request fixes.
=> Fix missing explicit instantiations

source/ElectronBeamHeatSource.hh, source/GoldakHeatSource.hh, source/ScanPath.hh, tests/test_implicit_operator.cc, tests/test_thermal_operator.cc, tests/test_thermal_operator_device.cc
I found the cause of the random failings in the CI. In some tests, we forgot to set the time at which the source should be evaluated. I have initialized member data in the sources to NaN which allowed me to find errors in `test_thermal_operator_device` and `test_implicit_operator` on top  of the known issue with `test_thermal_operator`.
=> Fix uninitialized variables

application/adamantine.hh, source/HeatSource.hh, source/ScanPath.cc, source/ScanPath.hh
@stvdwtt can you try this PR. With it you shouldn't need to restart adamantine to update the scan path.
=> Add support for the on-the-fly update of the scan path

application/adamantine.hh
This PR makes two small fixes involving restart:
- It removes the rank id from checkpoint filenames, this isn't needed and prevents loading the checkpoint at restart.
- It advances the experimental frame as necessary upon restart. Before this PR the code aborts when restarting after an experimental frame because it identifies an old, unassimilated frame.
I had to move the experiment block to after the restart block in initialization, this shows up in git as a somewhat convoluted change.
=> Restart fixes for experimental data and ensembles

README.md, application/adamantine.hh, source/ScanPath.cc, source/ScanPath.hh, source/utils.hh, source/validate_input_database.cc
With this PR, we stop reading the scan path when we read `SCAN_PATH_END`. When using `segment scan path`, we need the number of segments to be at least equal to number of  segments + 1. Otherwise we won't read the `SCAN_PATH_END` line.
@stvdwtt can you check that it works as you expect.
Fixes #223  and #272
=> Improve support for scan path update

application/CMakeLists.txt, source/CMakeLists.txt
IDE wasn't picking up the files for the Adamantine application or the headers. Linking them to the executable makes them show up.
=> Cmake adjustments

ci/jenkins_config, source/MaterialProperty.templates.hh, source/utils.hh
We are currently seeing
```
/var/jenkins/workspace/adamantine_PR-303/source/utils.hh:64:27: warning: catching polymorphic type 'class std::filesystem::__cxx11::filesystem_error' by value [-Wcatch-value=]
64 |   catch (std::filesystem::filesystem_error)
|                           ^~~~~~~~~~~~~~~~
```
in the CI.
=> CI: Use -Werror in CPU build

.github/workflows/Dockerfile
Work includes:
- adding a soft link in the Dockerfile for the adamantine executable so that you can just type `adamantine` anywhere in the container to run (instead of requiring to know the path `/home/adamantine/bin/adamantine` as it is currently)
This is mainly to help user experience for those that use the container + other container images that extend from this one (my current use case)
To test:
- Checkout branch
- Run `docker build -t adamantine-image -f ./ci/Dockerfile .` to build the container image
- Run `docker run adamantine-image adamantine` to test executable is available from default directory
- Run `docker run adamantine-image -w /change/to/path /bin/bash -c "pwd && adamantine"` to show adamantine is available even in a new directory
=> Sets adamantine as bin executable in Dockerfile

ci/Dockerfile
It seems that the link for the HDF5 download site has change for the `ci/Dockerfile`
To check:
- Clicking on https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.12/hdf5-1.12.0/src/hdf5-1.12.0.tar.bz2 will redirect you to https://www.hdfgroup.org/download/hdf5-1-12-0-tar-bz2/
- Clicking on https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.12/hdf5-1.12.0/src/hdf5-1.12.0.tar.bz2 gets you the direct download needed in the Dockerfile
This work includes:
- Switching the `HDF5_URL` environment variable URL prefix from `http://www.hdfgroup.org` to `https://support.hdfgroup.org` in `ci/Dockerfile`
=> Fixes HDF5 download site in ci/Dockerfile

source/ThermalOperator.templates.hh
I found the issue with the convective and radiative boundary conditions. There was a bug in `update_face_state_ratios`. We would go through the `Solid` state branch when we had `SolidLiquid` states. Because of that the liquid face state ratio was not initialized and we would get wrong material properties. I am going to rework some of our tests so we can catch that kind of issue next time.
=> Fix a bug in update_face_state_ratios

source/MechanicalPhysics.cc
Copying the parallel layout from `displacement`, we are missing some locally relevant DoFs we are accessing in `compute_stress`.
=> Use Vector with locally relevant dofs in compute_stress

application/adamantine.hh, indent
The indentation script didn't look at `adamantine.hh`.
=> Fix indentation for adamantine.hh

source/DataAssimilator.cc
This should fix https://github.com/adamantine-sim/adamantine/issues/335 @stvdwtt can you give this a try. 
I have removed extra `if (_global_rank == 0)`. These are unnecessary because they are inside a large `if (_global_rank == 0)`
=> Fix a bug when using more than 1 MPI rank per ensemble member

CHANGELOG.md
We had the changelog in the release branch but I forgot to cherry-pick it for `master`
=> Add changelog for release 1.0

doc/Doxyfile.in, doc/README.md, source/MaterialProperty.hh, source/MechanicalOperator.hh, source/ScanPath.hh, source/ThermalOperator.hh, source/ensemble_management.hh
This PR fixes Doxygen and stop printing full path of the directory where the Doxygen documentation was built.
=> Fix Doxygen warnings

application/adamantine.cc
Currently the code will crash if we pass an unknown option through the command line. In particular, this means that we cannot pass options to Kokkos. This PR fixes this issue.
=> Do not crash when passing kokkos options through the command line

application/adamantine.hh, source/ThermalPhysics.templates.hh
This was broken when `add_material` was split into `add_material_start` and `add_material_end`.
=> Fix Caliper add material region

application/adamantine.hh, source/ensemble_management.cc, source/ensemble_management.hh, tests/test_ensemble_management.cc
This PR does three things:
- Make sure that the variables are not correlated. Currently, if we call the function `get_normal_random_vector` twice in a row, we get the same values. This is because each call builds a new distribution using the same seed. Fix this issue by rejecting an increasing number of initial draws.
- Reject draws that return a negative value which are non-physical.  I am not sure if this is better or if we should just error out.
- For each ensemble member write a file with the data they used.
=> Rework ensembles

README.md, application/adamantine.hh, source/BeamHeatSourceProperties.hh, source/CubeHeatSource.cc, source/CubeHeatSource.hh, source/ElectronBeamHeatSource.cc, source/ElectronBeamHeatSource.hh, source/GoldakHeatSource.cc, source/GoldakHeatSource.hh, source/HeatSource.hh, source/ensemble_management.cc, source/ensemble_management.hh, source/validate_input_database.cc
There are two problems with the way AMR currently works:
1. each member refines its own mesh and therefore we cannot guarantee that all the members use the exact same mesh
2. the way we flag the cells for refinement is very inefficient. For each time step, we loop over the entire mesh to build a list of the cells that we need to refine.
To fix problem 1., we build bounding sources that bound the sources of all the ensemble members. We use these common sources to determine which cells need to be refined.
To fix problem 2., we use ArborX to compute the intersections of the bounding sources with the mesh. I decided to accumulated all the bounding sources before calling ArborX. This is to avoid calling ArborX with a single bounding box. In my tests, this works well if the number of time steps …
=> Use ArborX to find which cells to refine when using AMR

README.md, source/MaterialProperty.hh, source/MaterialProperty.templates.hh, tests/CMakeLists.txt, tests/data/material_property_polynomial.info, tests/data/material_property_table.info, tests/test_material_property.hh
This PR is related to https://github.com/adamantine-sim/adamantine/issues/357
- Do not use `;` as a delimiter when reading material properties because Boost thinks it is a comment. 
- Rewrite the tests to read from file instead of building a property tree in code. 
- Improve documentation
=> Fix input file when using temperature-dependent materiel properties

README.md, application/adamantine.hh, source/ensemble_management.cc, source/ensemble_management.hh, source/validate_input_database.cc, tests/data/bare_plate_L_da.info, tests/data/bare_plate_L_da_augmented.info, tests/data/bare_plate_L_ensemble.info, tests/data/integration_da_add_material.info, tests/test_ensemble_management.cc
This PR reworks how we set variables for data assimilation. Currently the variables that we can set are hard-coded, for instance `beam_0_max_power_stddev` sets the standard deviation for the maximum power of `beam_0`. Instead of hard-coding the values, this PR rework how we can set the standard deviation. With this PR, `beam_0_max_power_stddev` is replaced by `sources.beam_0.max_power_stddev`. The idea is to follow the naming scheme of the variable and to add `_stddev` at the end of the name. We then check that the original variable exists. Since nothing is hard-coded, more variables can be used for data assimilation. Note however that data assimilation only works for scalar values and therefore it does not work for temperature dependent variables.
=> Rework data assimilation variables

CMakeLists.txt
The new Docker image uses CMake 3.30 which introduces a new policy when searching for Boost. This PR sets this policy to new to quiet a warning from CMake.
=> Set CMake policy CMP0167 to new to quiet a warning from CMake

source/ElectronBeamHeatSource.cc, source/GoldakHeatSource.cc
The heat source contains an exponential and evaluating it is very expensive. We can get a 10% speedup in the operator evaluation by returning early if we know that the exponential will be close to zero.
=> Return early if the heat source is almost zero

CMakePresets.json, application/adamantine.cc, application/adamantine.hh, source/PostProcessor.cc, source/PostProcessor.hh, source/ensemble_management.cc
Split out of #364.
Allows for the explicit definition of the output directory via a '-o' flag on the command line. The quick implementation sticks the output dir in the input file ptree, so this has (unintended) side-effect of allowing configuration of the output directory from the .info file. The key is post_processing.output_dir.
Additionally, also makes a small change where if you call adamantine from a different directory than the .info file, it will change the PWD to that containing directory. This fixes a small bug where adamantine would just spin its heels waiting on files in the wrong locations.
=> Improved directory handling

README.md, application/adamantine.hh
With this PR, we output the solution just before and just after the data assimilation. This is on top of the "regular" outputs. This is on by default but it can be turned off to make a movie.
@stvdwtt I am not sure about the name of the input variable. If you have a better name, let me know.
=> Output solution just before and after data assimilation

.vscode/launch.json, .vscode/tasks.json
Split out of #364.
Adds vscode task and launch files that allow for testing from the GUI. These configs expect that you have the command-variable plugin installed.
Requires changes from #365 & #366 to be fully useful.
=> Basic VSCode tasks

source/Microstructure.hh
I didn't realize it but jenkins did not run when we merged https://github.com/adamantine-sim/adamantine/pull/384  Of course we merged code that does not compile with gcc :disappointed:
=> Add missing braces

application/adamantine.cc, application/adamantine.hh, source/Boundary.cc, source/DataAssimilator.cc, source/ThermalPhysics.templates.hh, source/validate_input_database.cc
When we print the message, we prepend it with `Error:`. Some error messages start with `Error:` and so we end up with something that looks like `Error: Error: Provided boundary id 10 is not valid`. This PR removes all the extra `Error:`
=> Remove extra Error: in the error message
